### ISSUE TITLE
Problem running code

### ISSUE THREAD

**Issue by amagrach** [CHoeppke/maxnodf#1]
I am trying to run the code you provide with my data but I have a problem with some of my networks because they do not satisfy the condition 'Links > nrow(web) + ncol(web). I am not sure I understand why this condition should be met. Any help will be really appreciated.

Thanks!

**Comment by SimmonsBI** [comment]
The reason for the condition:

    #Links(web) > #rows(web) + #cols(web)

comes from the initial condition chosen in the Song et. al. paper.

Their, and our, greedy algorithm starts from the network, where the top row and left hand column
are filled with 1's. Furthermore the entry web[[2, 2]] = 1 so that the initial network already contains
    #Links(web) = #rows(web) + #cols(web) + 1.

As we are only determining the positions of additional links to be placed in the network we get
that
    #Links(web) >= #rows(web) + #cols(web) + 1.

**Comment by SimmonsBI** [comment]
The reason for the condition:

#Links(web) > #rows(web) + #cols(web)

comes from the initial condition chosen in the Song et. al. paper.
Their, and our, greedy algorithm starts from the network, where the top row and left hand column
are filled with 1's. Furthermore the entry web[[1, 1]] = 1 so that the initial network already contains
    #Links(web) = #rows(web) + #cols(web) + 1.

As we are only determining the positions of additional links to be placed in the network we get
that
    #Links(web) >= #rows(web) + #cols(web) + 1.

**Comment by SimmonsBI** [comment]
The reason for the condition:

#Links(web) > #rows(web) + #cols(web)

comes from the initial condition chosen in Song, C, Rohr, RP, Saavedra, S. Why are some plant‐pollinator networks more nested than others? J Anim Ecol. 2017; 86: 1417– 1424.

Their, and our, greedy algorithm starts from the network, where the top row and left hand column
are filled with 1's. Furthermore the entry web[[2, 2]] = 1 so that the initial network already contains #Links(web) = #rows(web) + #cols(web) + 1.

As we are only determining the positions of additional links to be placed in the network we get
that
#Links(web) >= #rows(web) + #cols(web) + 1.
